new: Updated prepare-major-release for 13-play

diff --git a/prepare-major-release b/prepare-major-release
--- a/prepare-major-release
+++ b/prepare-major-release
@@ -8,31 +8,31 @@ reset
 set -e
 . build.env
 
-wipe_xh_known_hosts () {
-    echo "Cleaning previous entries from ~/.ssh/known_hosts"
-    ${RM_BIN} -f "${HOME}/.ssh/known_hosts"
-    return
-}
+# wipe_xh_known_hosts () {
+#     echo "Cleaning previous entries from ~/.ssh/known_hosts"
+#     ${RM_BIN} -f "${HOME}/.ssh/known_hosts"
+#     return
+# }
 
-no_vks_auth () {
-    echo "Local private SSH key file is required: ${HOME}/.ssh/${SSH_IDENTITY_FILE}"
-    echo "Generate it via 'ssh-keygen -t ed25519 && mv ~/.ssh/id_ed25519 ~/.ssh/${SSH_IDENTITY_FILE}' first!"
-    exit 101
-}
+# no_vks_auth () {
+#     echo "Local private SSH key file is required: ${HOME}/.ssh/${SSH_IDENTITY_FILE}"
+#     echo "Generate it via 'ssh-keygen -t ed25519 && mv ~/.ssh/id_ed25519 ~/.ssh/${SSH_IDENTITY_FILE}' first!"
+#     exit 101
+# }
 
-wipe_xh_known_hosts
-test -f "${HOME}/.ssh/${SSH_IDENTITY_FILE}" || no_vks_auth
-${CHMOD_BIN} 600 "${HOME}/.ssh/${SSH_IDENTITY_FILE}"
+# wipe_xh_known_hosts
+# test -f "${HOME}/.ssh/${SSH_IDENTITY_FILE}" || no_vks_auth
+# ${CHMOD_BIN} 600 "${HOME}/.ssh/${SSH_IDENTITY_FILE}"
 
-${GREP_BIN} "${HOSTADDR_NAME}" "${HOME}/.ssh/config" >/dev/null 2>&1
-if [ "${?}" != "0" ]; then
-    echo "Adding SSH entry: 'Host ${HOSTADDR_NAME} … hostname ${HOSTADDR_IP}'  to: ${HOME}/.ssh/config"
-    printf "\n%s\n%s\n%s\n" \
-        "host ${HOSTADDR_NAME}" \
-        "user root" \
-        "hostname ${HOSTADDR_IP}" \
-        >> "${HOME}/.ssh/config"
-fi
+# ${GREP_BIN} "${HOSTADDR_NAME}" "${HOME}/.ssh/config" >/dev/null 2>&1
+# if [ "${?}" != "0" ]; then
+#     echo "Adding SSH entry: 'Host ${HOSTADDR_NAME} … hostname ${HOSTADDR_IP}'  to: ${HOME}/.ssh/config"
+#     printf "\n%s\n%s\n%s\n" \
+#         "host ${HOSTADDR_NAME}" \
+#         "user root" \
+#         "hostname ${HOSTADDR_IP}" \
+#         >> "${HOME}/.ssh/config"
+# fi
 
 # Create home dataset: ${ZPOOL}${HOME_DIR}, dataset and switch as new default
 ${SSH_BIN} "${ADMIN_USER}@${HOSTADDR_NAME}" \
@@ -65,15 +65,15 @@ ${SSH_BIN} "${ADMIN_USER}@${HOSTADDR_NAME}" \
      ${PW_BIN} user mod toor -d '${HOME_DIR}'; \
      " && echo "New home dir: ${HOME_DIR}, ZFS dataset: '${ZPOOL}${HOME_DIR}/root'"
 
-${SCP_BIN} \
-    "${HOME}/.ssh/id_ed25519.pub" \
-    "${ADMIN_USER}@${HOSTADDR_NAME}:${HOME_DIR}/.ssh/authorized_keys" && \
-    echo 'Installed local ED25519 SSH key…'
+# ${SCP_BIN} \
+#     "${HOME}/.ssh/id_ed25519.pub" \
+#     "${ADMIN_USER}@${HOSTADDR_NAME}:${HOME_DIR}/.ssh/authorized_keys" && \
+#     echo 'Installed local ED25519 SSH key…'
 
-${SCP_BIN} \
-    "${HOME}/.ssh/${SSH_IDENTITY_FILE}" \
-    "${ADMIN_USER}@${HOSTADDR_NAME}:${HOME_DIR}/.ssh/${SSH_IDENTITY_FILE}" && \
-    echo 'Installed remote ED25519 SSH access key…'
+# ${SCP_BIN} \
+#     "${HOME}/.ssh/${SSH_IDENTITY_FILE}" \
+#     "${ADMIN_USER}@${HOSTADDR_NAME}:${HOME_DIR}/.ssh/${SSH_IDENTITY_FILE}" && \
+#     echo 'Installed remote ED25519 SSH access key…'
 
 echo
 echo
@@ -174,23 +174,23 @@ echo "Cleaning local archive…"
 ${RM_BIN} -f \
     ".archive-base-projects.tar.gz"
 
-PREVIOUS="FreeBSD-11.2-amd64"
+PREVIOUS="${SYSTEM_NAME}-12.2-amd64"
 GIT_VERSION="2.26.2"
 ZSH_VERSION="5.6.2"
-CCACHE_VERSION="3.7.1"
-MC_VERSION="4.8.23"
+CCACHE_VERSION="3.7.10"
+MC_VERSION="4.8.25"
 
 echo "Setting HOME to ${HOME_DIR}, Zsh as default shell, installing base software"
 ${SSH_BIN} "${ADMIN_USER}@${HOSTADDR_NAME}" \
     "${MKDIR_BIN} -p /${LAMBDA} ${CACHE_DIR} /etc/ssl; \
     ${FETCH_BIN} --no-verify-peer ${CACERT_SOURCE} -o /etc/ssl/cert.pem; \
     ${FETCH_BIN} -o ${CACHE_DIR}/Zsh${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Zsh-${ZSH_VERSION}-${PREVIOUS}${ZFSX_EXT}; ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Zsh; ${LZ4CAT_BIN} ${CACHE_DIR}/Zsh${ZFSX_EXT} | ${ZFS_BIN} receive ${ZPOOL}${SOFTWARE_DIR}/root/Zsh; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Zsh-common.zfsp ${SOFIN_BIN_REPO}/Common/Zsh-${ZSH_VERSION}.zfsp && ${LZ4CAT_BIN} ${CACHE_DIR}/Zsh-common.zfsp | ${ZFS_BIN} receive ${ZPOOL}${SERVICES_DIR}/root/Zsh; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Zsh-common.zfsp ${SOFIN_BIN_REPO}/Common/Zsh-${ZSH_VERSION}-${SYSTEM_NAME}.zfsp && ${LZ4CAT_BIN} ${CACHE_DIR}/Zsh-common.zfsp | ${ZFS_BIN} receive ${ZPOOL}${SERVICES_DIR}/root/Zsh; \
     ${FETCH_BIN} -o ${CACHE_DIR}/Ccache${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Ccache-${CCACHE_VERSION}-${PREVIOUS}${ZFSX_EXT}; ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Ccache; ${LZ4CAT_BIN} ${CACHE_DIR}/Ccache${ZFSX_EXT} | ${ZFS_BIN} receive ${ZPOOL}${SOFTWARE_DIR}/root/Ccache; \
     ${FETCH_BIN} -o ${CACHE_DIR}/Git${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Git-${GIT_VERSION}-${PREVIOUS}${ZFSX_EXT}; ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Git; ${LZ4CAT_BIN} ${CACHE_DIR}/Git${ZFSX_EXT} | ${ZFS_BIN} receive ${ZPOOL}${SOFTWARE_DIR}/root/Git; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Git-common.zfsp ${SOFIN_BIN_REPO}/Common/Git-${GIT_VERSION}.zfsp && ${LZ4CAT_BIN} ${CACHE_DIR}/Git-common.zfsp | ${ZFS_BIN} receive ${ZPOOL}${SERVICES_DIR}/root/Git; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Git-common.zfsp ${SOFIN_BIN_REPO}/Common/Git-${GIT_VERSION}-${SYSTEM_NAME}.zfsp && ${LZ4CAT_BIN} ${CACHE_DIR}/Git-common.zfsp | ${ZFS_BIN} receive ${ZPOOL}${SERVICES_DIR}/root/Git; \
     ${FETCH_BIN} -o ${CACHE_DIR}/Mc${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Mc-${MC_VERSION}-${PREVIOUS}${ZFSX_EXT}; ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Mc; ${LZ4CAT_BIN} ${CACHE_DIR}/Mc${ZFSX_EXT} | ${ZFS_BIN} receive ${ZPOOL}${SOFTWARE_DIR}/root/Mc; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Mc-common.zfsp ${SOFIN_BIN_REPO}/Common/Mc-${MC_VERSION}.zfsp && ${LZ4CAT_BIN} ${CACHE_DIR}/Mc-common.zfsp | ${ZFS_BIN} receive ${ZPOOL}${SERVICES_DIR}/root/Mc; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Mc-common.zfsp ${SOFIN_BIN_REPO}/Common/Mc-${MC_VERSION}-${SYSTEM_NAME}.zfsp && ${LZ4CAT_BIN} ${CACHE_DIR}/Mc-common.zfsp | ${ZFS_BIN} receive ${ZPOOL}${SERVICES_DIR}/root/Mc; \
     ${MKDIR_BIN} -p ${SERVICES_DIR}/Git/etc/ssl; \
     ${CP_BIN} -v /etc/ssl/cert.pem ${SERVICES_DIR}/Git/etc/ssl/cert.pem; \
     ${SED_BIN} -i '' -e 's|^/bin/tcsh|${DEFAULT_SHELL}|g' /etc/shells; \
@@ -218,7 +218,7 @@ ${SSH_BIN} "${ADMIN_USER}@${HOSTADDR_NAME}" \
     ${ZFS_BIN} set primarycache=metadata ${ZPOOL}/ROOT; \
     ${ZFS_BIN} set secondarycache=none ${ZPOOL}/ROOT; \
     ${ZFS_BIN} set checksum=off ${ZPOOL}/ROOT; \
-    ${ZFS_BIN} set recordsize=16k ${ZPOOL}/ROOT; \
+    ${ZFS_BIN} set recordsize=4k ${ZPOOL}/ROOT; \
     ${ZFS_BIN} set sync=disabled ${ZPOOL}/ROOT; \
     ${ZFS_BIN} set readonly=off ${ZPOOL}/ROOT; \
     echo 'Cleanup…'; \
