new: Merged build-* scripts into build-base. Cleanup, switch to safe system upgrades.

diff --git a/prepare-major-release b/prepare-major-release
--- a/prepare-major-release
+++ b/prepare-major-release
@@ -11,6 +11,18 @@ echo "Preparing dirs…"
 ${SSH_BIN} root@xh1 \
     "${MKDIR_BIN} -p ${CACHE_DIR} ${HOME_DIR}/.ssh"
 
+no_vks_auth () {
+    echo "Local private SSH RSA key file is required: ${HOME}/.ssh/vks.auth"
+    echo "Generate it via 'ssh-keygen -b4096' first!"
+    exit 101
+}
+test -f "${HOME}/.ssh/vks.auth" || no_vks_auth
+
+echo 'Installing RSA remote key…'
+${SCP_BIN} \
+    "${HOME}/.ssh/vks.auth" \
+    "root@xh1:${HOME_DIR}/.ssh/vks.auth"
+
 echo 'Installing ED25519 SSH key…'
 ${SCP_BIN} \
     "${HOME}/.ssh/id_ed25519.pub" \
@@ -54,7 +66,7 @@ for _dataset_origin in Software Services User; do
 
     ${SSH_BIN} root@xh1 "${ZFS_BIN} list ${ZPOOL}/${_dataset_origin}/root" >/dev/null 2>&1
     if [ "${?}" != "0" ]; then
-        echo "Creating ${ZPOOL}/${_dataset_origin} origin"
+        echo "Creating ${ZPOOL}/${_dataset_origin} ${ORIGIN}"
         ${SSH_BIN} root@xh1 \
             "${ZFS_BIN} create \
             -o readonly=off \
@@ -122,13 +134,13 @@ MC_VERSION="4.8.18-master"
 
 echo "Setting HOME to ${HOME_DIR}, Zsh as default shell, installing base software"
 ${SSH_BIN} root@xh1 \
-    "${FETCH_BIN} -o ${CACHE_DIR}/Zsh${ZFSX_EXT} http://software.verknowsys.com/binary/${PREVIOUS}/Zsh-${ZSH_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Zsh && ${XZCAT_BIN} ${CACHE_DIR}/Zsh${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Zsh; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Zsh-common.zfsp http://software.verknowsys.com/binary/Common/Zsh-${ZSH_VERSION}.zfsp && ${XZCAT_BIN} ${CACHE_DIR}/Zsh-common.zfsp | ${ZFS_BIN} receive -vF ${ZPOOL}${SERVICES_DIR}/root/Zsh; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Ccache${ZFSX_EXT} http://software.verknowsys.com/binary/${PREVIOUS}/Ccache-${CCACHE_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Ccache && ${XZCAT_BIN} ${CACHE_DIR}/Ccache${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Ccache; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Git${ZFSX_EXT} http://software.verknowsys.com/binary/${PREVIOUS}/Git-${GIT_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Git && ${XZCAT_BIN} ${CACHE_DIR}/Git${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Git; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Git-common.zfsp http://software.verknowsys.com/binary/Common/Git-${GIT_VERSION}.zfsp && ${XZCAT_BIN} ${CACHE_DIR}/Git-common.zfsp | ${ZFS_BIN} receive -vF ${ZPOOL}${SERVICES_DIR}/root/Git; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Mc${ZFSX_EXT} http://software.verknowsys.com/binary/${PREVIOUS}/Mc-${MC_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Mc && ${XZCAT_BIN} ${CACHE_DIR}/Mc${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Mc; \
-    ${FETCH_BIN} -o ${CACHE_DIR}/Mc-common.zfsp http://software.verknowsys.com/binary/Common/Mc-${MC_VERSION}.zfsp && ${XZCAT_BIN} ${CACHE_DIR}/Mc-common.zfsp | ${ZFS_BIN} receive -vF ${ZPOOL}${SERVICES_DIR}/root/Mc; \
+    "${FETCH_BIN} -o ${CACHE_DIR}/Zsh${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Zsh-${ZSH_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Zsh && ${XZCAT_BIN} ${CACHE_DIR}/Zsh${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Zsh; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Zsh-common.zfsp ${SOFIN_BIN_REPO}/Common/Zsh-${ZSH_VERSION}.zfsp && ${XZCAT_BIN} ${CACHE_DIR}/Zsh-common.zfsp | ${ZFS_BIN} receive -vF ${ZPOOL}${SERVICES_DIR}/root/Zsh; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Ccache${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Ccache-${CCACHE_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Ccache && ${XZCAT_BIN} ${CACHE_DIR}/Ccache${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Ccache; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Git${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Git-${GIT_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Git && ${XZCAT_BIN} ${CACHE_DIR}/Git${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Git; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Git-common.zfsp ${SOFIN_BIN_REPO}/Common/Git-${GIT_VERSION}.zfsp && ${XZCAT_BIN} ${CACHE_DIR}/Git-common.zfsp | ${ZFS_BIN} receive -vF ${ZPOOL}${SERVICES_DIR}/root/Git; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Mc${ZFSX_EXT} ${SOFIN_BIN_REPO}/${PREVIOUS}/Mc-${MC_VERSION}-${PREVIOUS}${ZFSX_EXT} && ${ZFS_BIN} destroy -r ${ZPOOL}${SOFTWARE_DIR}/root/Mc && ${XZCAT_BIN} ${CACHE_DIR}/Mc${ZFSX_EXT} | ${ZFS_BIN} receive -vF ${ZPOOL}${SOFTWARE_DIR}/root/Mc; \
+    ${FETCH_BIN} -o ${CACHE_DIR}/Mc-common.zfsp ${SOFIN_BIN_REPO}/Common/Mc-${MC_VERSION}.zfsp && ${XZCAT_BIN} ${CACHE_DIR}/Mc-common.zfsp | ${ZFS_BIN} receive -vF ${ZPOOL}${SERVICES_DIR}/root/Mc; \
     ${SED_BIN} -i '' -e 's|^/bin/tcsh|${DEFAULT_SHELL}|g' /etc/shells; \
     ${CHSH_BIN} -s ${DEFAULT_SHELL} root; \
     ${TAR_BIN} xfJ ${CACHE_DIR}/.archive-base-projects.tar.xz --directory / >/dev/null; \
@@ -147,8 +159,6 @@ ${SSH_BIN} root@xh1 \
     ${LN_BIN} -fvs /etc/zsh/zshrc /etc/zshrc; \
     printf 'Host *.verknowsys.com verknowsys.com\nPort 60022\n\n' > ${HOME_DIR}/.ssh/config; \
     ${SYSCTL_BIN} vfs.zfs.prefetch_disable=1; \
-    ${SYSCTL_BIN} debug.witness.trace=0; \
-    ${SYSCTL_BIN} debug.witness.watch=0; \
     ${SYSCTL_BIN} hardening.pax.pageexec.status=1; \
     ${SYSCTL_BIN} hardening.pax.mprotect.status=1; \
     ${SYSCTL_BIN} hardening.pax.aslr.status=1; \
